### ISSUE TITLE
Problems running openapi command

### ISSUE THREAD

**Issue by ClaireBoulter** [Redocly/openapi-cli#218]
I am working through an online course, evaluating Redocly:

https://idratherbewriting.com/learnapidoc/pubapis_redocly.html

In the Redocly CLI Walkthrough tutorial, I have successfully completed 1. Install the prerequisites and 2. Break up an OpenAPI file.

(To create the repository, I used npx create-openapi-repo as recommended in the online course. To install openapi-cli, I used npx @redocly/openapi-cli lint openapi_openweathermap.yml.)

However, in step 3 of 3. Check your OpenAPI definition against rules, I get the following error when I change to the directory containing my project and type openapi lint at the terminal prompt:

'openapi' is not recognized as an internal or external command,
operable program or batch file.

Can anyone advise what I need to do to resolve the problem running openapi commands?

**Comment by adamaltman** [comment]
Hi @ClaireBoulter it sounds like you're almost there.

There are five ways to run `openapi-cli`:

1. Install it globally. `npm install -g @redocly/openapi-cli`. I do this because I use openapi-cli all the time. I am also cautious to update it to the latest version when a new version is released. `npm update -g @redocly/openapi-cli` or by specifying a version like `npm update -g @redocly/openapi-cli@1.0.0-beta.16`. Doing this will allow you to use `openapi` from your CLI. You can test it by running `openapi --version`.

2. Use `npx` -- it is slower for each run because it will download and install openapi-cli temporarily when you use it. It only adds a five or so seconds. `npx @redocly/openapi-cli --version`.

3. To test your API definitions from the repo folder itself, you could run `npm test`, which runs `openapi-cli` (see the `package.json` which explains the script "test" shortcut). 

4. Run openapi-cli using the local installation (it will require the path to the install cli.js file). Here is an example from within a project directory: **node_modules > @redocly > openapi-cli > lib > cli.js**

    ```
    node_modules/@redocly/openapi-cli/lib/cli.js --version
    1.0.0-beta.16
    ```

5. Hook your GitHub repo to our Redocly app and setup a starter account on app.redoc.ly and get continuous validation of your OpenAPI definitions. Then, you're also only one step away from the docs. 

Personally, I use option 1 and 5 together.

**Comment by ClaireBoulter** [comment]
Hi Adam,

Thank you for that. Option 1 worked for me with the files I created locally.

I will consider following options 1 and 5 in future.

Regards
Claire
T: +44 (0)1635 826009
M: +44 (0)7954 189710
