### ISSUE TITLE
Lint incorrectly reports 'schema' and 'required' for 'headers' added by reference

### ISSUE THREAD

**Issue by Piranit** [Redocly/openapi-cli#533]
**Describe the bug**
We have two OAS Schemas, one is with pagination headers definitions, second is where we used these pagination headers.

Lint passed successfully for pagination headers definitions OAS file, but in another file, when we try to make reference to this headers definition, lint triggers errors for this header definitions.

**To Reproduce**
1. Create OAS Schema with headers.
2. Use this OAS Schema by reference in another OAS Schema file.
3. Run lint command: `npx @redocly/openapi-cli@latest lint filename.v1.oas3.yml --extends minimal`
3. Lint will trigger errors.

**Expected behavior**
Lint passes successfully.

**Error Logs**
```
  {
    "ruleId": "spec",
    "severity": "error",
    "message": "Property `schema` is not expected here.",
    "suggest": [],
    "location": [
      {
        "source": {
          "ref": "https:/api.redoc.ly/registry/dat/custom_registry/v1/bundle/main/openapi.json"
        },
        "pointer": "#/components/headers/PaginationLink/schema",
        "reportOnKey": true
      }
    ]
  },
  {
    "ruleId": "spec",
    "severity": "error",
    "message": "Expected type `array` but got `boolean`.",
    "location": [
      {
        "source": {
          "ref": "https:/api.redoc.ly/registry/custom_registry/v1/bundle/main/openapi.json"
        },
        "pointer": "#/components/headers/PaginationLink/required",
        "reportOnKey": false
      }
    ],
    "suggest": []
  }
```

**OpenAPI definition**
**Note that all unnecessary sections were skipped.**

File definition 1
```
{
  "openapi": "3.0.0",
  "paths": {},
  "components": {
    "headers": {
      "PaginationLink": {
        "description": "A link header will be returned specifying the first page (if not this one), previous page (if available), next page (if available) and last page (if not this one).",
        "schema": {
          "type": "string"
        },
        "required": true
      }
    }
  }
}
```

File definition 2
```
{
  "openapi": "3.0.0",
  "paths": {},
  "components": {
    "headers": {
      "PaginationLink": {
        "$ref": "https://api.redoc.ly/registry/custom_registry/v1/bundle/main/openapi.json#/components/headers/PaginationLink"
      }
    }
  }
}
```

**`openapi-cli` Version(s)**
Latest. Used via npx. 1.0.0-beta.80

**`Node.js` Version(s)**
v14.17.3

**Comment by adamaltman** [comment]
I could not reproduce this one. 

I made two OpenAPI files:

### `base.yaml`

```yaml
openapi: 3.0.0
info:
  title: Test Base
  version: v1
paths: {}
components:
  headers:
    PaginationLink:
      description: A link header will be returned specifying the first page (if not this one), previous page (if available), next page (if available) and last page (if not this one).
      schema:
        type: string
      required: true
```

### `consumer.yaml`

```yaml
openapi: 3.0.0
info:
  title: Test Consumer
  version: v1
paths: {}
components:
  headers:
    PaginationLink:
      $ref: https://api.redoc.ly/registry/bundle/testing_acme/cli533/base/openapi.json?branch=main#/components/headers/PaginationLink
```

Running `lint` and `bundle` are both successful. A couple of changes from what was posted above -- most notably was adding the `info` section (which is required in OpenAPI 3.0) and I assume you actually had it but redacted it.

Two possibilites:

1. The registry URL looks unusual -- but I assume you redacted it -- I did not redact mine in the example above. Please copy the registry URL and try it again.
2. The registry URL is probably private, and you may need to run the [login command](https://redoc.ly/docs/cli/commands/login/) before linting since it consumes a private registry url.

It could be something else... but I don't know what.

The registry also detected the usages as I would have expected in the example:

<img width="628" alt="2022-01-27_19-11-53" src="https://user-images.githubusercontent.com/1161871/151469560-9a1ddffe-0cb6-4153-9984-f6df5c9bed24.png">

**Comment by Piranit** [comment]
@adamaltman thanks for your quick response.
After your answer, we double-checked our case.
There was a problem with the usage.

Correct usage:
```
"headers": {
  "Link": {
    "$ref": "#/components/headers/Pagination-Link"
  }
}
```
Incorrect usage:
```
"headers": {
  "Link": {
    "schema": {
      "$ref": "#/components/schemas/Pagination-Link"
    },
  }

}
```
