### ISSUE TITLE
merge allOf while bundling

### ISSUE THREAD

**Issue by MarcLevisse** [Redocly/openapi-cli#629]
Is there a way to ask openapi-cli bundle command to merge allOf ?
We use bundle command to merge external references, but while using the resulting OAS in our HTTP requests/responses validation process (using Atlassian's swagger-request-validation lib) we would like to be able to merge allOf into single object (so as validation does not reject jsons that matches "whole allOf object's properties" but no "each allOf object's properties one by one"

I know that sort of thing is a rather common need, as I've read here and there while dealing about usage (good or bad) of allOf

I don't know if openapi-cli is based (or should take advantage of) json-schema-merge-allOf lib
And if not built-in, do you see a way to implement it, perhaps using custom plugin/decorator ?

Thx for your insights !

**Comment by RomanHotsiy** [comment]
Hi @MarcLevisse.

No, merging oneOf is a very complicated and error-prone. And also it can't be done reliably all the time.

We merge allOfs in our reference docs where the correctness of the resulting schema is not so important and I think it works good enough in 99% of real cases. We use our own code as oas 3.0 used it's own subset of json-schema and we needed more control of the process.

We need to rewrite the corresponding code as it is really messy at this point and then maybe we'll move it into separate package.

You can try to use `json-schema-merge-allOf` as a custom decorator.

I would advise you against merging it though. What is your use case? Do you need it to work with some tool that has a poor support of allOf? Most of the validation tools support it nicely (because it was designed for validation) while any other tools have troubles.
